### ISSUE TITLE
Create a Random class

### ISSUE THREAD

**Issue by MarkOates** [MarkOates/allegro_flare#88]
move the random functions from `useful.h` in there.

**Comment by arvidsson** [comment]
I have a Random class using STL <random> if that would be of interest :)

**Comment by MarkOates** [comment]
That sounds awesome!  Where can I find it?

I'm also thinking about grouping the encryption functions in this `Random` class as well for hashing strings to generate random output.

**Comment by arvidsson** [comment]
It's in my io repo: https://github.com/arvidsson/io/blob/master/io/math/Random.hpp

Feel free to use and adapt, it's just a very basic wrapper anyways. Or I can take a stable and contribute according to your coding standard in flare.

**Comment by MarkOates** [comment]
That's really nice, actually. 👌 👍 

AllegroFlare hasn't reached stable yet.  I do `push -f` on rebases from time to time, but anything up to https://github.com/MarkOates/allegro_flare/commit/14c703f3116442c3c4a237828f2faf89faf71694 (the latest commit right now) is safe.

The plan is that everything is in a bit of refactory-limbo until `v0.9`.

**Comment by arvidsson** [comment]
It would be fun to contribute and collaborate. I like the idea of flare being a c++ allegro app and game framework with useful stuff where you can kinda pick and choose what you need.

**Comment by MarkOates** [comment]
I agree.  I alway find that when it comes time to make a game/app, instead of creating the game, I spend 90% of my time _creating a thing_ so that I can create my game.  The objective of AllegroFlare is to have many of those things already made, and ready to go, so you can focus just on making the game.

**Comment by MarkOates** [comment]
Fixed in https://github.com/MarkOates/allegro_flare/pull/115 🎉
